Only restart the cluster when absolutely necessary, otherwise reload. See: https://github.com/ANXS/postgresql/pull/294

diff --git a/tasks/configure.yml b/tasks/configure.yml
--- a/tasks/configure.yml
+++ b/tasks/configure.yml
@@ -80,6 +80,8 @@
   become: yes
   become_user: "{{ postgresql_service_user }}"
   when: ansible_os_family == "Debian" and postgresql_cluster_reset and pgdata_dir_exist.changed
+  register: postgresql_cluster_startup_conf
+  notify: restart postgresql
 
 - name: PostgreSQL | Update systemd | Debian
   command: systemctl daemon-reload
@@ -134,6 +136,7 @@
     group: "{{ postgresql_service_group }}"
     mode: 0640
   register: postgresql_configuration_pt1
+  notify: reload postgresql
 
 - name: PostgreSQL | Update configuration - pt. 2 (postgresql.conf)
   template:
@@ -144,6 +147,38 @@
     group: "{{ postgresql_service_group }}"
     mode: 0640
   register: postgresql_configuration_pt2
+  notify: reload postgresql
+
+- name: PostgreSQL | Update configuration - pt. 3 (pgtune)
+  become: true
+  become_user: "{{ postgresql_service_user }}"
+  shell: |
+    set -e
+    TMPDIR=$(mktemp -d)
+    pgtune --input-config=postgresql.conf.untuned\
+           --output-config=$TMPDIR/postgresql.conf\
+           {% if postgresql_pgtune_memory %}--memory {{postgresql_pgtune_memory|int}}{% endif %}\
+           --type {{postgresql_pgtune_type|quote}}\
+           {% if postgresql_pgtune_connections %}--connections {{postgresql_pgtune_connections|int}}{% endif %}\
+    # Compare the current config with the one procuded by pgtune (ignoring comments/blanks)
+    if diff --ignore-blank-lines \
+        <(sed -e 's/#.*//' postgresql.conf) \
+        <(sed -e 's/#.*//' $TMPDIR/postgresql.conf)
+    then
+      echo '_OK_'
+    else
+      cp $TMPDIR/postgresql.conf postgresql.conf
+    fi
+    # Cleanup
+    rm $TMPDIR/postgresql.conf
+    rmdir $TMPDIR
+  args:
+    chdir: "{{postgresql_conf_directory}}"
+    executable: "/bin/bash"
+  when: postgresql_pgtune
+  register: postgresql_configuration_pt3
+  notify: reload postgresql
+  changed_when: "'_OK_' not in postgresql_configuration_pt3.stdout"
 
 - name: PostgreSQL | Update configuration - pt. 3 (pgtune)
   become: true
@@ -201,12 +236,19 @@
   when: ansible_os_family == "RedHat"
   notify: restart postgresql
 
-- name: PostgreSQL | Use the conf directory when starting the Postgres service | RedHat
+- name: PostgreSQL | Use the conf directory when starting the PostgreSQL service | RedHat
   template:
     src: etc_systemd_system_postgresql.service.d_custom.conf.j2
     dest: "/etc/systemd/system/postgresql-{{ postgresql_version }}.service.d/custom.conf"
   when: ansible_os_family == "RedHat"
   register: postgresql_systemd_custom_conf
+  notify: restart postgresql
+
+- name: PostgreSQL | Reload systemd daemon | systemd
+  systemd:
+    daemon-reload: yes
+  when: ansible_service_mgr == 'systemd' and
+        postgresql_systemd_custom_conf.changed
 
 - name: PostgreSQL | Ensure the pid directory for PostgreSQL exists
   file:
@@ -217,8 +259,36 @@
     mode: u=rwX,g=rwXs,o=rx
   notify: restart postgresql
 
+- name: PostgreSQL | Enable service
+  service:
+    name: "{{ postgresql_service_name }}"
+    enabled: yes
+  when: postgresql_service_enabled
+
+- name: PostgreSQL | Ensure PostgreSQL is running
+  service:
+    name: "{{ postgresql_service_name }}"
+    state: started
+  register: postgresql_cold_started
+
 - name: PostgreSQL | Reload all conf files
   service:
     name: "{{ postgresql_service_name }}"
     state: reloaded
-  when: postgresql_configuration_pt1.changed or postgresql_configuration_pt2.changed or postgresql_configuration_pt3.changed or postgresql_systemd_custom_conf.changed
+  notify: reload postgresql
+  when: not postgresql_cold_started.changed and
+        ( postgresql_configuration_pt1.changed or
+          postgresql_configuration_pt2.changed or
+          postgresql_configuration_pt3.changed or
+          postgresql_systemd_custom_conf.changed)
+
+- name: PostgreSQL | Check for parameter changes that require a restart | >= v9.5
+  become: yes
+  become_user: "{{ postgresql_service_user }}"
+  shell: "{{ postgresql_bin_directory }}/psql postgres --username {{ postgresql_admin_user }} --tuples-only --command='SELECT count(*) COUNT FROM pg_settings WHERE pending_restart IS true;'"
+  register: postgresql_check_for_param_changes
+  notify: reload postgresql
+  when: not postgresql_cold_started.changed and
+        postgresql_version is version('9.5','>=')
+  changed_when: postgresql_check_for_param_changes.rc == 0 and
+                postgresql_check_for_param_changes.stdout | replace (' ','') != "0"
